[workspace]
members = ["cargo:crates/ws-cli"]

[dist]
cargo-dist-version = "0.30.4"
ci = "github"
installers = ["shell", "homebrew"]
tap = "langify-org/homebrew-tap"
publish-jobs = ["homebrew"]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
]
pr-run-mode = "plan"
