[book]
title = "ws - workspace マネージャー"
authors = ["langify-org"]
language = "ja"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/langify-org/ws-cli"
edit-url-template = "https://github.com/langify-org/ws-cli/edit/master/docs/{path}"
default-theme = "light"
preferred-dark-theme = "navy"
